Repository we-write/frontend, pull requests merged in 2025-07, with the labels that each got.

#183 Fix/#291: 특정 상황에서 GNB의 프로필 이미지가 잘려보이는 현상 수정
  src/components/layout/GNB/LoginSection.tsx
Labels: Review-Applied

#186 Feature/#67: 로그인 폼 이메일 기억하기 추가
  src/api/auth/type.ts
  src/app/auths/signin/_components/SignInForm.tsx
  src/app/auths/signin/_components/SigninForm.test.tsx
  src/hooks/api/auth/useSignInForm.ts
Labels: LGTM(지혁)

#189 Chore/#295: README 기술스택에 Zustand 추가
  README.md
Labels: Please-Merge, LGTM(수영)

#191 Feature/#298: Middleware로 서버측 리다이렉션 적용 구현
  middleware.ts
  package-lock.json
  package.json
  src/app/auths/signin/page.tsx
  src/app/auths/signup/page.tsx
  src/app/mypage/page.tsx
  src/app/social/page.tsx
  src/components/layout/GNB/UserProfileDropdown.tsx
  src/components/logic/RedirectErrorToastHandler.tsx
  src/hooks/api/auth/usePostSignin.ts
  src/middleware.ts
  src/utils/middleware-utils.ts
Labels: Review-Applied
