Repository we-write/frontend, pull requests merged in 2025-06, with the labels that each got.

#30 Feat: 로그아웃 기능구현
  src/api/auth.ts
  src/constants/apiPath.ts
  src/hooks/api/users/usePostSignout.ts
Labels: enhancement

#38 Feat: 내 프로필 조회, 수정 구현
  public/assets/icons/BtnEditLarge.svg
  public/assets/icons/BtnEditSmall.svg
  public/assets/icons/index.ts
  public/assets/images/BtnEdit.png
  public/assets/images/Profile.png
  src/api/auth.ts
  src/app/mypage/myProfile/EditMyProfileForm.tsx
  src/app/mypage/myProfile/MyProfile.tsx
  src/app/mypage/myProfile/MyProfileSkeleton.tsx
  src/app/mypage/myProfile/type.ts
  src/app/mypage/page.tsx
  src/components/layout/GNB/GNB.tsx
  src/components/layout/GNB/LoginSection.tsx
  src/components/layout/GNB/type.ts
  src/constants/apiPath.ts
  src/hooks/api/users/useUpdateMyInfo.ts
  src/types/user.ts
Labels: enhancement

#50 Feat: 모임 상세 페이지 소개글(Summary) 등록, 출력 구현
  package-lock.json
  package.json
  src/api/social-detail/api.ts
  src/api/social-detail/type.ts
  src/app/social/detail/[socialId]/StorySummary.tsx
  src/app/social/detail/[socialId]/page.tsx
  src/app/social/detail/[socialId]/type.ts
  src/components/common/TextEditor/TextEditor.tsx
  src/constants/queryKey.ts
  src/hooks/api/teams/useGetSummary.ts
  src/hooks/api/teams/useSaveSummary.ts
Labels: Review-In-Progress, LGTM(명헌)

#44 Feat: 모임 상세 페이지 타이틀 기능 및 UI 구현
  package-lock.json
  package.json
  src/api/social-detail/api.ts
  src/api/social-detail/type.ts
  src/api/social/type.ts
  src/app/social/SocialFilterBar.tsx
  src/app/social/SocialList.tsx
  src/app/social/detail/[socialId]/SocialOverView.tsx
  src/app/social/detail/[socialId]/StorySummary.tsx
  src/app/social/detail/[socialId]/page.tsx
  src/app/social/detail/[socialId]/type.ts
  src/components/common/AvatarGroup/AvatarGroup.tsx
  src/components/common/Card/DetailCard.tsx
  src/components/common/Card/type.ts
  src/components/common/TextEditor/TextEditor.tsx
  src/constants/queryKey.ts
  src/hooks/api/teams/useGetSocialDetail.ts
  src/hooks/api/teams/useGetSocialParticipants.ts
  src/hooks/api/teams/useGetSummary.ts
  src/hooks/api/teams/useJoinTeam.tsx
  src/hooks/api/teams/useSaveSummary.ts
  src/lib/getQueryClient.ts
  src/utils/convertLocationToGenre.ts
  src/utils/extractUserImages.ts
Labels: Review-In-Progress, LGTM(명헌)

#56 Fix: 모임 상세 페이지 실제 URL과 Card컴포넌트에 적용된 Link href가 다른 문제 수정
  src/components/common/Card/GridCard.tsx
  src/components/common/Card/ListCard.tsx
Labels: Please-Merge

#65 Feat: 스토리 아이디를 통한 컨텐츠 병합 함수 추가
  src/api/stories/api.ts
Labels: LGTM(명헌), LGTM(지혁)

#60 Fix: ListCard이미지 스타일 에러 수정
  src/components/common/Card/ListCard.tsx
Labels: Review-Applied, LGTM(수영)

#67 Feat: library 내 검색, 장르 필터 기능
  src/api/stories/api.ts
  src/api/stories/type.ts
  src/app/library/_components/BadgeGroup.tsx
  src/app/library/_components/LibraryListGrid.tsx
  src/app/library/_components/SearchInput.tsx
  src/app/library/_components/type.ts
  src/app/library/page.tsx
  src/hooks/library/useInfiniteStories.ts
  src/hooks/library/useSearchReducer.ts
  src/hooks/stories/useGetStories.ts
  src/utils/htmlToString.ts
Labels: Please-Merge

#64 fix: 로그인 상태 유지 수정
  src/app/layout.tsx
  src/components/layout/GNB/GNB.tsx
  src/components/layout/GNB/LoginSection.tsx
  src/hooks/api/users/useGetMyInfo.ts
  src/hooks/api/users/usePostSignin.ts
  src/hooks/api/users/usePostSignout.ts
  src/providers/userInfoProvider.tsx
  src/utils/authContext.tsx
Labels: Please-Merge, Review-Applied

#74 Refactor: 모임 상세 페이지 소개글 영역에 반응형 padding, margin 적용
  src/app/social/detail/[socialId]/StorySummary.tsx
Labels: Please-Merge

#68 Feat: 모임찾기 반응형 스타일 추가
  src/app/social/SocialList.tsx
Labels: LGTM(수영)

#51 Feat: 모달 입력필드 추가 및 반복되는 로직 컴포넌트 분리
  src/api/social/api.ts
  src/api/social/type.ts
  src/api/stories/api.ts
  src/api/stories/type.ts
  src/api/story-collaborators/api.ts
  src/api/story-collaborators/type.ts
  src/app/social/SocialListContainer.tsx
  src/app/social/createSocialForm/CreateSocialForm.stories.tsx
  src/app/social/createSocialForm/CreateSocialForm.tsx
  src/app/social/createSocialForm/DropdownInput.tsx
  src/app/social/createSocialForm/SocialForm.tsx
  src/app/social/createSocialForm/StorySettingForm.tsx
  src/app/social/createSocialForm/type.ts
  src/app/social/createSocialForm/useCreateSocialForm.ts
  src/constants/apiPath.ts
  src/constants/social/createSocialForm.ts
  src/types/teamUserRole.ts
Labels: Review-Applied

#73 Fix: 모임 상세 페이지의 텍스트 에디터 내부 입력 영역이 에디터 컨테이너를 초과하는 문제 수정
  src/components/common/TextEditor/TextEditor.tsx
Labels: Please-Merge

#82 Fix: Modal 열릴 시 배경 스크롤 제어
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/type.ts
Labels: LGTM(명헌), LGTM(지혁), LGTM(수영)

#89 Fix: 캘린더 유효성 검사 트리거 에러 수정
  src/app/social/createSocialForm/useCreateSocialForm.ts
  src/components/common/Calendar/Calendar.tsx
Labels: LGTM(지혁)

#80 fix: 스토리 상세 페이지로 경로 변경
  src/app/library/_components/LibraryListGrid.tsx
  src/app/social/SocialList.tsx
  src/components/common/Card/GridCard.stories.tsx
  src/components/common/Card/GridCard.tsx
  src/components/common/Card/type.ts
Labels: LGTM(지혁), LGTM(한옥)

#84 Fix: 비로그인시 mypage에서 로그인페이지로 redirect
  src/app/mypage/page.tsx
Labels: LGTM(수영)

#86 Fix: 소개글 및 작성글 빈 값으로 요청이 보내지는 문제 수정 (글자 수 제한 적용)
  src/app/library/detail/[id]/_components/CreateContentModal.tsx
  src/app/social/detail/[socialId]/StorySummary.tsx
  src/components/common/TextEditor/TextEditor.tsx
  src/types/textEditor.ts
  src/utils/validators/validateEditorContent.ts
Labels: Please-Merge, LGTM(수영)

#90 Fix: 회원가입 유효성 검사 수정
  src/api/auth.ts
  src/app/auths/signup/page.tsx
Labels: LGTM(명헌)

#92 fix: 로그인 모바일 사이즈 수치 조정
  src/app/auths/signin/page.tsx
Labels: Please-Merge

#93 Feat: 모임 참여에 성공하면 DB 테이블에 사용자 정보가 입력되는 기능 구현
  src/api/story-collaborators/api.ts
  src/api/story-collaborators/type.ts
  src/app/social/createSocialForm/useCreateSocialForm.ts
  src/app/social/detail/[socialId]/SocialOverView.tsx
  src/app/social/detail/[socialId]/page.tsx
  src/app/social/detail/[socialId]/type.ts
  src/hooks/api/teams/useParticipateCollaborator.ts
Labels: LGTM(명헌)

#94 Fix: 다른 아이디로 로그인해도 GNB와 마이페이지에선 회원정보가 변하지 않는 문제
  src/constants/queryKey.ts
  src/hooks/api/users/useGetMyInfo.ts
  src/hooks/api/users/usePostSignout.ts
Labels: Please-Merge, LGTM(명헌), LGTM(한옥)

#101 Fix: 모임 생성 직후 작성된 글이 존재하지 않을 때, 컨텐츠 작성이 불가능한 문제 수정
  src/app/library/detail/[id]/_components/CreateContentModal.tsx
  src/app/library/detail/[id]/_components/WritableUserModal.tsx
  src/app/library/detail/[id]/_components/type.ts
Labels: Please-Merge, LGTM(명헌)

#81 Fix: 모임 요약 데이터 표시
  src/api/stories/api.ts
  src/app/social/SocialList.tsx
  src/constants/queryKey.ts
  src/hooks/api/stories/useGetSocialSummary.ts
Labels: Please-Merge, Review-Applied

#107 Fix: 모임 참여 실패후에 db에 저장되는 이슈
  src/app/social/detail/[socialId]/SocialOverView.tsx
Labels: LGTM(한옥)

#108 fix: 승인 인원이 달성됐을 때 실제 병합 처리
  src/hooks/api/content-approvals/useApproveContent.ts
Labels: Please-Merge

#109 Fix: 모임 참여에 성공했을 때, alert출력, UI 반영 적용
  src/api/story-collaborators/api.ts
  src/app/social/detail/[socialId]/SocialOverView.tsx
  src/hooks/api/teams/useJoinTeam.tsx
  src/hooks/api/teams/useParticipateCollaborator.ts
Labels: Please-Merge

#111 Feat: 에디터를 통한 텍스트 작성 시에 글자 수 제한 적용
  src/app/library/detail/[id]/_components/CreateContentModal.tsx
  src/app/library/detail/[id]/_components/WritableUserModal.tsx
  src/app/library/detail/[id]/_components/type.ts
  src/app/library/detail/[id]/page.tsx
  src/components/common/TextEditor/TextEditor.tsx
  src/components/common/TextEditor/type.ts
Labels: LGTM(수영)

#112 fix: 컨텐츠 등록 직후에 승인 인원수가 0이 아닌 1로 표시되는 문제 수정
  src/app/library/detail/[id]/_components/WritableUserModal.tsx
Labels: LGTM(한옥), LGTM(수영)

#115 Fix: mysocialist 내 삭제된 모임 표시 안되게 처리
  src/api/mypage/type.ts
  src/app/mypage/myProfile/MyProfile.tsx
  src/app/mypage/mySocial/MySocialList.tsx
Labels: LGTM(명헌), LGTM(수영)

#124 Chore: PR템플릿 수정
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
Labels: LGTM(수영)

#123 Refactor: 타입 컨벤션에 맞게 리팩토링
  src/api/social/api.ts
  src/api/social/type.ts
  src/app/auths/signin/page.tsx
  src/app/auths/signup/page.tsx
  src/app/layout.tsx
  src/app/library/detail/[id]/_components/ContentComponent.tsx
  src/app/library/detail/[id]/_components/ContentCover.tsx
  src/app/library/detail/[id]/_components/PaginationControl.tsx
  src/app/library/detail/[id]/_components/SideButtonGroup.tsx
  src/app/library/detail/[id]/_components/type.ts
  src/app/mypage/_components/myProfile/EditMyProfileForm.tsx
  src/app/mypage/_components/mySocial/type.ts
  src/app/page.tsx
  src/app/social/_components/create-social-form/useCreateSocialForm.ts
  src/app/social/_components/social-list/SocialInfiniteScrollFeed.tsx
  src/app/social/_components/type.ts
  src/components/common/Button/Button.tsx
  src/components/common/Calendar/Calendar.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/type.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/type.ts
  src/components/layout/GNB/type.ts
  src/components/layout/LayoutWrapper.tsx
  src/components/layout/SideDrawer/type.ts
  src/hooks/api/social/useGetSocialList.ts
  src/hooks/api/supabase/stories/useGetSocialSummary.ts
  src/providers/auth-provider/AuthProvider.client.tsx
  src/providers/auth-provider/type.ts
  src/utils/isServr.ts
Labels: LGTM(한옥)

#119 Fix: 모임작성하기 드롭다운 겹침 현상
  src/app/social/_components/create-social-form/DropdownInput.tsx
  src/app/social/_components/create-social-form/SocialForm.tsx
  src/components/common/Dropdown/Dropdown.tsx
  src/components/common/Dropdown/type.ts
Labels: Review-Applied, LGTM(명헌), LGTM(한옥)

#126 Fix: 회원가입 완료시 경로 수정
  src/app/auths/signup/page.tsx
Labels: Review-Applied, LGTM(명헌), LGTM(한옥)

#130 Fix/#232: 모임 참여 버튼 클릭 시에 서로 다른 alert 가 연달아 출력되는 문제 수정
  src/app/social/detail/[socialId]/_components/SocialOverView.tsx
  src/hooks/api/social/useJoinTeam.ts
Labels: Please-Merge, LGTM(한옥)

#114 Feat: DB에서 모임 삭제하는 로직 구현, 사용할 수 없는 모임 삭제 버튼에 대한 UI 표시 적용
  src/api/social-detail/api.ts
  src/api/social-detail/type.ts
  src/app/social/detail/[socialId]/_components/SocialOverView.tsx
  src/components/common/Card/DetailCard.tsx
  src/hooks/api/supabase/useDeleteSocialByDb.ts
Labels: LGTM(명헌)

#131 Fix/#235: 텍스트 에디터의 아무 위치나 클릭해도 커서(focus)가 활성화되도록 수정
  src/components/common/TextEditor/TextEditor.tsx
  src/components/common/TextEditor/type.ts
Labels: Review-Applied, LGTM(명헌)

#143 Feature/#233: Toast 구현
  src/app/layout.tsx
  src/components/ui/ToastMessage.stories.ts
  src/components/ui/ToastMessage.tsx
  src/providers/ToastProvider.tsx
  src/styles/globals.css
  src/types/toastType.ts
  src/utils/toast.ts
Labels: Please-Merge, Review-Applied

#146 Refactor/#252: 로그인 페이지 리팩토링
  src/api/auth/type.ts
  src/app/auths/_components/FormField.tsx
  src/app/auths/_components/PasswordFormField.tsx
  src/app/auths/_components/type.ts
  src/app/auths/signin/_components/LinkToSignUp.tsx
  src/app/auths/signin/_components/SignInForm.tsx
  src/app/auths/signin/page.tsx
  src/app/auths/signup/_components/SignupForm.tsx
  src/hooks/api/auth/usePostSignin.ts
  src/hooks/api/auth/useSignInForm.ts
  src/utils/validators/auth.ts
  src/utils/validators/type.ts
Labels: Please-Merge, Review-Applied

#153 Refactor/#261: default layout 설정 추가 및 수정
  src/app/library/detail/[id]/page.tsx
  src/app/not-found.tsx
  src/app/social/detail/[socialId]/_components/SocialOverView.tsx
  src/components/layout/LayoutWrapper.tsx
Labels: Please-Merge

#142 Fix/#246: gnb 프로필 사이즈 수정, rounded 적용
  src/components/layout/GNB/LoginSection.tsx
  src/components/layout/GNB/UserDropdown.tsx
Labels: Review-Applied

#144 Refactor/#249: 회원가입 페이지 리팩토링
  src/api/auth/type.ts
  src/app/auths/signin/_components/LinkToSignUp.tsx
  src/app/auths/signin/_components/SignInForm.tsx
  src/app/auths/signin/page.tsx
  src/app/auths/signup/_components/LinkToSignIn.tsx
  src/app/auths/signup/_components/SignupForm.tsx
  src/app/auths/signup/page.tsx
  src/hooks/api/auth/useCreateUser.ts
  src/hooks/api/auth/usePostSignin.ts
  src/hooks/api/auth/useSignInForm.ts
  src/hooks/api/auth/useSignUpForm.ts
  src/utils/validators/auth.ts
  src/utils/validators/type.ts
Labels: Review-Applied

#159 Refactor/#263: social페이지 socialId > storyId로 변경
  src/api/instance.ts
  src/app/social/_components/social-list/SocialListGrid.tsx
  src/constants/queryKey.ts
  src/hooks/api/auth/useGetMyInfo.ts
  src/hooks/api/supabase/stories/useGetStoryIdList.ts
  src/providers/auth-provider/getMyInfoOnServer.ts
Labels: Please-Merge

#149 Refactor: library 페이지 리팩토링
  src/api/stories/api.ts
  src/api/stories/type.ts
  src/app/library/_components/BadgeGroup.tsx
  src/app/library/_components/GenreBadge.tsx
  src/app/library/_components/LibraryListContainer.tsx
  src/app/library/_components/LibraryListGrid.tsx
  src/app/library/_components/LibraryListSkeleton.tsx
  src/app/library/_components/SearchInput.tsx
  src/app/library/_components/type.ts
  src/app/library/page.tsx
  src/hooks/api/library/useInfiniteStories.ts
  src/hooks/api/library/useSearchReducer.ts
Labels: Review-Applied

#150 Refactor/#259: 스토리 상세 페이지 표지 컴포넌트 리팩토링
  src/app/library/detail/[id]/_components/ContentCover.tsx
  src/app/library/detail/[id]/_components/PaginationControl.tsx
  src/app/library/detail/[id]/_components/SideButtonGroup.tsx
  src/app/library/detail/[id]/page.tsx
Labels: Please-Merge

#151 Feature/#260: 스토리 좋아요 기능 추가
  src/api/stories/api.ts
  src/app/library/detail/[id]/_components/ModalToSigin.tsx
  src/app/library/detail/[id]/_components/SideButtonGroup.tsx
  src/app/library/detail/[id]/type.ts
  src/constants/queryKey.ts
  src/hooks/api/library/useLikeStory.ts
  src/types/dbStory.ts
Labels: Review-Applied

#168 Chore#268: README 파일 추가
  README.md
Labels: Please-Merge

#176 refactor/#271: mypage noImage 처리, alert를 toast로 대체
  src/api/mypage/api.ts
  src/app/mypage/_components/my-social-list/MySocialListCardItem.tsx
  src/components/common/Card/ListCard.tsx
  src/hooks/api/auth/useUpdateMyInfo.ts
Labels: Review-Applied

#182 Chore/#290: main에 병합된 Hotfix/#285 변경사항을 develop 브랜치에 반영
  src/api/stories/api.ts
  src/app/library/detail/[id]/_components/CreateContentModal.tsx
  src/app/library/detail/[id]/_components/StoryModalTriggerButton.tsx
  src/app/library/detail/[id]/_components/WritableUserModal.tsx
  src/app/library/detail/[id]/page.tsx
Labels: Please-Merge
